### PR TITLE
Adding example application and support for choosing color selection

### PR DESCRIPTION
**Pull request by vsoch**
This PR will address #19. Overall we do the following:

 - add an "example" application folder that serves a Dockerized image with the example "polls" that asks the user for a favorite color. Two images are pre-built and provided on [Docker Hub](https://hub.docker.com/r/vanessa/django-colorfield/) so the user can quickly preview. Full instructions and a walkthrough with pictures are also provided, or just do:

```
docker run -d -p 8000:8000 vanessa/django-colorfield:palette
docker run -d -p 8000:8000 vanessa/django-colorfield:selection
```
Note that above uses a single django image with sqlite3, a more substantial application should use a real database :)

 - changes the default guts of the plugin from jscolor to [spectrum](https://bgrins.github.io/spectrum/). jscolor seems to be a lot more limited in functionality. I also had quite a bit of trouble getting the static files to be added to the application, and think a simpler approach is to use a CDN.

I overall had some trouble figuring out how to generate the form, or customize it. This can be a different PR (note that I filed an issue #37 ) but I think it would be good to have a few examples of how to do this. If Django needs custom configuration for the templates (e.g., to be findable from an egg), this needs to be documented.

### CODE REVIEW

**Comment by fabiocaccamo** [comment]
@vsoch Spectrum has not been updated since 4 years, so it is not a possible candidate to replace `jscolor`.

**Comment by vsoch** [comment]
And your review of this just one short of that! lol. Thanks anyway I guess... :/

**Comment by fabiocaccamo** [comment]
I'm sorry, the development of this package has been in pause for long time, there are bigger problems to solve before changing color-picker.
Anyway I'm going to release a new version in the next days, stay tuned.

**Comment by vsoch** [comment]
That’s great news!

**Comment by fabiocaccamo** [comment]
I just released `0.2.0` version, could you check it please?

**Comment by vsoch** [comment]
I'm not actively using this anymore (for a few years now) but if I ever give it another go, I'd be happy to give feedback.

**Pull request closed without merging**
